storage.dir = D:/basejava/storage
#db.url = jdbc:postgresql://localhost:5432/resumes
#db.user = postgres
#db.password = postgres
db.url = jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/d5s986m5ht0djo
db.user = qaqiarkcblllan
db.password = b3dcc858fb2be527858875ad3409206e37bf275bd39d44f669a1de442efbf90a